/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from './IERC20__factory.js';
export { WalletContract__factory } from './WalletContract__factory.js';