/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowContractInterface extends Interface {
    getFunction(nameOrSignature: "createOrder" | "getBalance" | "getOrder" | "markDisputed" | "orders" | "refundFunds" | "relayer" | "releaseFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeOpened" | "FundsRefunded" | "FundsReleased" | "OrderCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createOrder', values: [BytesLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'markDisputed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'orders', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'refundFunds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDisputed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
  }

  
    export namespace DisputeOpenedEvent {
      export type InputTuple = [orderId: BytesLike];
      export type OutputTuple = [orderId: string];
      export interface OutputObject {orderId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsRefundedEvent {
      export type InputTuple = [orderId: BytesLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, seller: string, amount: bigint];
      export interface OutputObject {orderId: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [orderId: BytesLike, providerWallet: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, providerWallet: string, amount: bigint];
      export interface OutputObject {orderId: string, providerWallet: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCreatedEvent {
      export type InputTuple = [orderId: BytesLike, seller: AddressLike, providerWallet: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, seller: string, providerWallet: string, amount: bigint];
      export interface OutputObject {orderId: string, seller: string, providerWallet: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowContract;
    waitForDeployment(): Promise<this>;

    interface: EscrowContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createOrder: TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, providerWallet: AddressLike, ],
      [void],
      'payable'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {seller: string, providerWallet: string, amount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >
    

    
    markDisputed: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {seller: string, providerWallet: string, amount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >
    

    
    refundFunds: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseFunds: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [orderId: BytesLike, seller: AddressLike, providerWallet: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {seller: string, providerWallet: string, amount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'markDisputed'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {seller: string, providerWallet: string, amount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'refundFunds'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeOpened'): TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
getEvent(key: 'FundsRefunded'): TypedContractEvent<FundsRefundedEvent.InputTuple, FundsRefundedEvent.OutputTuple, FundsRefundedEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;

    filters: {
      
      'DisputeOpened(bytes32)': TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
      DisputeOpened: TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
    

      'FundsRefunded(bytes32,address,uint256)': TypedContractEvent<FundsRefundedEvent.InputTuple, FundsRefundedEvent.OutputTuple, FundsRefundedEvent.OutputObject>;
      FundsRefunded: TypedContractEvent<FundsRefundedEvent.InputTuple, FundsRefundedEvent.OutputTuple, FundsRefundedEvent.OutputObject>;
    

      'FundsReleased(bytes32,address,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'OrderCreated(bytes32,address,address,uint256)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    
    };
  }