/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GeneratorFactoryContractInterface extends Interface {
    getFunction(nameOrSignature: "generate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "WalletGenerated"): EventFragment;

    encodeFunctionData(functionFragment: 'generate', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'generate', data: BytesLike): Result;
  }

  
    export namespace WalletGeneratedEvent {
      export type InputTuple = [wallet: AddressLike];
      export type OutputTuple = [wallet: string];
      export interface OutputObject {wallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GeneratorFactoryContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): GeneratorFactoryContract;
    waitForDeployment(): Promise<this>;

    interface: GeneratorFactoryContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    generate: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'generate'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'WalletGenerated'): TypedContractEvent<WalletGeneratedEvent.InputTuple, WalletGeneratedEvent.OutputTuple, WalletGeneratedEvent.OutputObject>;

    filters: {
      
      'WalletGenerated(address)': TypedContractEvent<WalletGeneratedEvent.InputTuple, WalletGeneratedEvent.OutputTuple, WalletGeneratedEvent.OutputObject>;
      WalletGenerated: TypedContractEvent<WalletGeneratedEvent.InputTuple, WalletGeneratedEvent.OutputTuple, WalletGeneratedEvent.OutputObject>;
    
    };
  }