/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as walletContractSol from './WalletContract.sol/index.js';
export type { walletContractSol };
export type { EscrowContract } from './EscrowContract.js';
export type { GeneratorFactoryContract } from './GeneratorFactoryContract.js';
export * as factories from './factories/index.js';
export { GeneratorFactoryContract__factory } from './factories/GeneratorFactoryContract__factory.js';
export { EscrowContract__factory } from './factories/EscrowContract__factory.js';
export type { IERC20 } from './WalletContract.sol/IERC20.js';
export { IERC20__factory } from './factories/WalletContract.sol/IERC20__factory.js';
export type { WalletContract } from './WalletContract.sol/WalletContract.js';
export { WalletContract__factory } from './factories/WalletContract.sol/WalletContract__factory.js';