/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface WalletContractInterface extends Interface {
    getFunction(nameOrSignature: "forwardToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositedOnMetaDapp" | "TokenForwarded"): EventFragment;

    encodeFunctionData(functionFragment: 'forwardToken', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'forwardToken', data: BytesLike): Result;
  }

  
    export namespace DepositedOnMetaDappEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenForwardedEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, amount: bigint];
      export interface OutputObject {token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WalletContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): WalletContract;
    waitForDeployment(): Promise<this>;

    interface: WalletContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    forwardToken: TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'forwardToken'): TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositedOnMetaDapp'): TypedContractEvent<DepositedOnMetaDappEvent.InputTuple, DepositedOnMetaDappEvent.OutputTuple, DepositedOnMetaDappEvent.OutputObject>;
getEvent(key: 'TokenForwarded'): TypedContractEvent<TokenForwardedEvent.InputTuple, TokenForwardedEvent.OutputTuple, TokenForwardedEvent.OutputObject>;

    filters: {
      
      'DepositedOnMetaDapp()': TypedContractEvent<DepositedOnMetaDappEvent.InputTuple, DepositedOnMetaDappEvent.OutputTuple, DepositedOnMetaDappEvent.OutputObject>;
      DepositedOnMetaDapp: TypedContractEvent<DepositedOnMetaDappEvent.InputTuple, DepositedOnMetaDappEvent.OutputTuple, DepositedOnMetaDappEvent.OutputObject>;
    

      'TokenForwarded(address,uint256)': TypedContractEvent<TokenForwardedEvent.InputTuple, TokenForwardedEvent.OutputTuple, TokenForwardedEvent.OutputObject>;
      TokenForwarded: TypedContractEvent<TokenForwardedEvent.InputTuple, TokenForwardedEvent.OutputTuple, TokenForwardedEvent.OutputObject>;
    
    };
  }